# Generated by Django 4.2.3 on 2023-07-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rephraser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_with_children', models.CharField(max_length=255, null=True)),
                ('good_with_other_dogs', models.CharField(max_length=100)),
            ],
        ),
    ]
